/*
 * Copyright 2026 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { createMockDirectory } from '@backstage/backend-test-utils';
import { join as joinPath } from 'node:path';
import { PnpmLockfile } from './PnpmLockfile';

describe('PnpmLockfile', () => {
  const mockDir = createMockDirectory();

  it('should read package names and versions from a lockfile', async () => {
    // Generated by pnpm 12.4.2 in a workspace that pins pnpm through the
    // packageManager field, which makes pnpm write two YAML documents
    const lockfile = await PnpmLockfile.load(
      joinPath(__dirname, '__fixtures__', 'pnpm-lock.yaml'),
    );

    expect([...lockfile.keys()].sort()).toEqual([
      'is-number',
      'is-odd',
      'js-tokens',
      'kind-of',
      'loose-envify',
      'react',
      'react-dom',
      'scheduler',
    ]);
    expect(lockfile.get('is-number')).toEqual([
      { version: '6.0.0' },
      { version: '7.0.0' },
    ]);
    expect(lockfile.get('react-dom')).toEqual([{ version: '18.3.1' }]);
    expect(lockfile.get('pnpm')).toBeUndefined();
    expect(lockfile.get('@pnpm/exe.linux-x64')).toBeUndefined();
    expect(lockfile.get('nonexistent')).toBeUndefined();
  });

  it('should reject lockfiles that cannot be read', async () => {
    mockDir.setContent({
      'old.yaml': `lockfileVersion: '6.0'\n`,
      'broken.yaml': `packages: [\n`,
      'entry.yaml': `lockfileVersion: '9.0'\npackages:\n  nope: {}\n`,
    });

    await expect(
      PnpmLockfile.load(mockDir.resolve('old.yaml')),
    ).rejects.toThrow("Unsupported pnpm lockfile version '6.0'");
    await expect(
      PnpmLockfile.load(mockDir.resolve('broken.yaml')),
    ).rejects.toThrow('Failed pnpm-lock.yaml parse');
    await expect(
      PnpmLockfile.load(mockDir.resolve('entry.yaml')),
    ).rejects.toThrow("Failed to parse pnpm-lock.yaml entry 'nope'");
  });
});
