/*
 * Copyright 2026 The Backstage Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { overrideTargetPaths } from '@backstage/cli-common/testUtils';
import {
  detectPackageManager,
  PackageGraph,
  YarnLockfile,
} from '@backstage/cli-node';
import info from './info';

jest.mock('@backstage/cli-node', () => ({
  ...jest.requireActual('@backstage/cli-node'),
  detectPackageManager: jest.fn(),
}));

const lockfileContents = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"@backstage/core@^1.0.5":
  version "1.0.6"

"@backstage/theme@^1.0.0":
  version "1.0.0"

"@backstage/theme@^2.0.0":
  version "2.0.0"

"@backstage/local@workspace:packages/local":
  version "0.0.0-use.local"

"lodash@^4.17.21":
  version "4.17.21"
`;

function mockPackageManager(name: string, version: string) {
  jest.mocked(detectPackageManager).mockResolvedValue({
    name: () => name,
    version: () => version,
    loadLockfile: async () => YarnLockfile.parse(lockfileContents),
  } as unknown as Awaited<ReturnType<typeof detectPackageManager>>);
}

const commandInfo = { usage: 'backstage-cli info', name: 'info' };

describe('info', () => {
  overrideTargetPaths('/nonexistent-target-root');

  let logs: string[];

  beforeEach(() => {
    logs = [];
    jest.spyOn(console, 'log').mockImplementation((...args) => {
      logs.push(args.join(' '));
    });
    jest.spyOn(PackageGraph, 'listTargetPackages').mockResolvedValue([
      {
        dir: '/nonexistent-target-root/packages/local',
        packageJson: { name: '@backstage/local', version: '0.3.0' },
      },
    ]);
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  // The command never resolves, so we wait for its output instead
  function runForJsonOutput(args: string[]): Promise<any> {
    return new Promise(resolve => {
      jest.spyOn(process.stdout, 'write').mockImplementation(chunk => {
        resolve(JSON.parse(String(chunk)));
        return true;
      });
      info({ args, info: commandInfo });
    });
  }

  function runForTextOutput(args: string[]): Promise<string[]> {
    return new Promise(resolve => {
      jest.spyOn(console, 'log').mockImplementation((...logArgs) => {
        logs.push(logArgs.join(' '));
        // Everything after the first line is written synchronously
        if (logArgs[0]?.startsWith('OS:')) {
          setImmediate(() => resolve(logs));
        }
      });
      info({ args, info: commandInfo });
    });
  }

  it('reports the detected package manager, keeping the yarn field for Yarn', async () => {
    mockPackageManager('yarn', '4.1.0');

    const output = await runForJsonOutput(['--format', 'json']);
    expect(output.system).toEqual(
      expect.objectContaining({
        node: process.version,
        yarn: '4.1.0',
        packageManager: { name: 'yarn', version: '4.1.0' },
        backstage: 'N/A',
      }),
    );
    expect(output.dependencies).toEqual({
      '@backstage/core': [{ version: '1.0.6' }],
      '@backstage/theme': [{ version: '1.0.0' }, { version: '2.0.0' }],
    });
    expect(output.local).toEqual({
      '@backstage/local': [{ version: '0.3.0' }],
    });

    const textLogs = await runForTextOutput([]);
    expect(textLogs).toEqual(
      expect.arrayContaining([
        `node: ${process.version}`,
        'yarn: 4.1.0',
        'backstage:   N/A',
        'Dependencies:',
        '  @backstage/core  1.0.6',
        '  @backstage/theme 1.0.0, 2.0.0',
        'Local:',
        '  @backstage/local 0.3.0',
      ]),
    );
  });

  it('omits the yarn field for other package managers', async () => {
    mockPackageManager('pnpm', '12.4.2');

    const output = await runForJsonOutput(['--format', 'json']);
    expect(output.system).not.toHaveProperty('yarn');
    expect(output.system.packageManager).toEqual({
      name: 'pnpm',
      version: '12.4.2',
    });

    const textLogs = await runForTextOutput([]);
    expect(textLogs).toContain('pnpm: 12.4.2');
    expect(textLogs).not.toContain('yarn: 12.4.2');
  });
});
